[package]
name = "alaska"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["compiler"]

[dependencies]
compiler = { path = "compiler" }

[dev-dependencies]
unindent = "0.2.3"
criterion = "0.5.1"

[[bench]]
name = "main"
path = "compiler/src/benches/main.rs"
harness = false
