[package]
name = "alaska"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["compiler-core"]

[dependencies]
compiler-core = { path = "compiler-core" }
structopt = "0.3.24"
anyhow = "1.0.44"

[[bench]]
name = "main"
path = "compiler/src/benches/main.rs"
harness = false
